### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by ltfafei** [LubyRuffy/gofofa#6]
建议--fofaURL选项可以改为从一个配置文件中加载，而不是每次都要在命令行输入，体验不太友好。

**Comment by LubyRuffy** [comment]
@ltfafei 谢谢反馈，尽快加上。你觉得是程序同目录下面的config.yml这种方式好，还是~/.gofofa/config.yml这种方式好？如果有时间，能否帮忙写代码提交mr？

另外，其实是支持环境变量的，比如：
```
go install github.com/LubyRuffy/gofofa/cmd/fofa@latest
FOFA_CLIENT_URL='https://fofa.info/?email=xxx@gmail.com&key=xxx' $GOPATH/bin/fofa search port=80
```
