### ISSUE TITLE
BUG 【没有翻页功能】

### ISSUE THREAD

**Issue by ltfafei** [LubyRuffy/gofofa#7]
输出的第一页IP之后，后面的80条数据都是同一个IP，另外建议增加URL选项。

指令：fofa.exe --fofaURL "https://fofa.info/?email=xxx&key=9fxxxxxx6&version=v1" search "title=Gitblit" --size 100

![image](https://user-images.githubusercontent.com/43526141/176084825-9ac5450e-fe90-4ace-a117-1e359215f7bc.png)

**Comment by LubyRuffy** [comment]
感谢反馈，增加url选项是指输出都变成有http://这样的前缀吗？

另外，确实没有设置翻页，我想的是你只需要输入你想导出的数据量就可以了。

最后，你的这个命令行需要修改：
```
fofa.exe --fofaURL "https://fofa.info/?email=xxx&key=9fxxxxxx6&version=v1" search "title=Gitblit" --size 100
```
改成：
```
fofa.exe --fofaURL "https://fofa.info/?email=xxx&key=9fxxxxxx6&version=v1" search --size 100 "title=Gitblit"
```
配置要在query前面，配置项之后的所有内容会作为查询语句进行处理。

**Comment by LubyRuffy** [comment]
v0.1.11 版本增加了相关的命令行参数：
```
./fofa --size 2 --fields "host" --fixUrl title=Gitblit
http://47.92.145.232:8998
https://114.55.35.145:8443
```

@ltfafei 帮忙确认一下是否满足需求，如果ok我就把issue关了 ；）
